FROM node:17-alpine
WORKDIR "/app/frontend"

# necessario descomentar quando clonar projeto do react
# COPY package.json .

# RUN npm install

# COPY . .

EXPOSE 3000
# mesmo caso mencionado acima
# CMD ["npm", "start"]